#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
send_metrics = false

# This is a Pages project, so we don't need to specify a main entry point
# Deployment will be handled by `wrangler pages deploy build/client`
