#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

# Cloudflare Pages Configuration
[site]
bucket = "./build/client"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
